info:
  component: Zuul Server

# Service Info
spring:
  profiles:
    active: local
  application:
    name: Zuul

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  sensitiveHeaders: Cookie, Set-Cookie
  routes:
    auth:
      path: /auth/**
      serviceId: AUTHSERVICE
    config:
      path: /config/**
      serviceId: CONFIGSERVER
    hystrix:
      path: /hystrix/**
      serviceId: HYSTRIXDASHBOARD
    ordering:
      path: /ordering/**
      serviceId: ORDERING-MICROSERVICE
    shoppingcart:
      path: /shoppingcart/**
      serviceId: SHOPPINGCART-MICROSERVICE
    warehouse:
      path: /warehouse/**
      serviceId: WAREHOUSE-MICROSERVICE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
---
spring:
  profiles: docker
eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka/
---
spring:
  profiles: local

server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: vm
eureka.client.serviceUrl.defaultZone: http://${eureka.address}:8761/eureka/
