package edu.hm.ba.kongo.shop.shoppingcart.guilib.services;


import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import edu.hm.ba.kongo.shop.shoppingcart.client.local.Cart_;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Cart_FallbackDataGenerator{
	
	/** Fallback-Daten generierung. Diese Methoden werden durch Barrakuda mit dem gewünschten Verhalten befüllt. */
	
	
	/**
	 * Generiert Fallback-Daten für Methoden, die einen einzelnen Cart_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Cart_ createCartFallback(){
		return null;
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die eine Liste von Cart_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static List<Cart_> createCartsFallback(){
		return new ArrayList<>();
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die ein Optional von Cart_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Optional<Cart_> createOptionalCartFallback(){
		return Optional.empty();
	}
	
}
