package edu.hm.ba.kongo.shop.shoppingcart.service.services.resource;

import org.springframework.hateoas.Resource;
import org.springframework.stereotype.Service;

import edu.hm.ba.kongo.shop.shoppingcart.service.gen.domain.Cart_;
import edu.hm.ba.kongo.shop.shoppingcart.service.gen.services.resource.Cart_ResourceService;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
/**
 * Provides methods to alter resources before being sent to a client.
 * If used as generated by GAIA this service will be autowired and called by Cart_ResourceProcessor.
 */
@Service
public class Cart_ResourceServiceImpl implements Cart_ResourceService {
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	
	/**
	 * Process a resource.
	 * You can add links and alter the entity itself.
	 * When used as generated by GAIA this method will be called whenever a resource is sent to a client.
	 */
	public Resource<Cart_> process(Resource<Cart_> resource){
		// Implement your logic here.
		return resource;
	}
}
