package edu.hm.ba.kongo.shop.ordering.service.services.event;

import org.springframework.stereotype.Service;

import edu.hm.ba.kongo.shop.ordering.service.gen.domain.OrderingItem_;
import edu.hm.ba.kongo.shop.ordering.service.gen.services.event.OrderingItem_EventService;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by OrderingItem_EventListener.
 */
@Service
public class OrderingItem_EventServiceImpl implements OrderingItem_EventService{
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(OrderingItem_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(OrderingItem_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(OrderingItem_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(OrderingItem_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(OrderingItem_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(OrderingItem_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(OrderingItem_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(OrderingItem_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(OrderingItem_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(OrderingItem_ parent, Object linked) {
		// Add your logic here.
	}
}
