package edu.hm.ba.kongo.shop.ordering.service.services.event;

import org.springframework.stereotype.Service;

import edu.hm.ba.kongo.shop.ordering.service.gen.domain.Order_;
import edu.hm.ba.kongo.shop.ordering.service.gen.services.event.Order_EventService;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by Order_EventListener.
 */
@Service
public class Order_EventServiceImpl implements Order_EventService{
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(Order_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(Order_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(Order_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(Order_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(Order_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(Order_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(Order_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(Order_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(Order_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(Order_ parent, Object linked) {
		// Add your logic here.
	}
}
