package edu.hm.ba.kongo.shop.warehouse.client.rest;

import edu.hm.ba.kongo.shop.warehouse.client.local.Product_;
import org.springframework.hateoas.Link;

import java.util.Collection;
import java.util.List;
import java.util.Optional;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public interface Product_RestClient {

    /**
     * The name of the Base Endpoint
     */
    public static final String PRODUCTS = "products";

    /**
     * Get all the Products (with matching tenancy).
     *
     * @return a List of all Products.
     */
    List<Product_> findAll();

    /**
     * Get all the Products (with matching tenancy) on a specific endpoint.
     * <p>
     *     For example: <code>http://localhost:80/entitys/1/attribute</code>
     * </p>
     * @param relation
     * @return
     */
    List<Product_> findAll(Link relation);
    
    /**
     * Get all Product matched with string due to fuzzy search.
     * @param filter the string for the query
     * @return
     */
    List<Product_> findFullTextFuzzy(String filter);

    /**
     * Try to find one Product (with matching tenancy) by its ID / self relation.
     *
     * @param link The ID / self relation of the Product_.
     * @return an optional of the Product_.
     */
    Optional<Product_> findOne(Link link);

    /**
     * Set all the relations, specified by links, on a specific relation endpoint.
     * <p>
     * Example for an Endpoint: <code>http://localhost:80/entitys/1/attribute</code>
     * </p>
     * <p>
     * This method will always (re-) set the associations. The add or delete
     * functionality is not provided at RestClient level.
     * </p>
     *
     * @param endpoint The endpoint of the relation.
     * @param links    The links that are set to be related.
     */
    void setRelations(Link endpoint, Collection<Link> links);
	/**
	 * Set the relation, specified by @relation, on a specific relation endpoint.
	 * <p>
	 * Example for an Endpoint: <code>http://localhost:80/entitys/1/attribute</code>
	 * </p>
	 * <p>
	 * This method will always (re-) set the association. The add or delete
	 * functionality is not provided at RestClient level.
	 * </p>
	 *
	 * @param endpoint The endpoint of the relation.
	 * @param relation    The link that is set to be related.
	 */
	void setRelation(Link endpoint, Link relation);
    /**
     * Create a new Product_, the returned Product_ will have the Links and its ID.
     * @param product The Product_ to create, it must not contain any links.
     * @return the created Product_ (with ID).
     */
    Product_ create(Product_ product);

    /**
     * Update the fields of a Product_ by the {@link Product_#getId()}.
     *
     * @param product The updated Product_ that will be saved.
     * @return the updated version from the REST Server.
     */
    Product_ update(Product_ product);

    /**
     * Try to delete an ID.
     * @param id The link to the id.
     */
    void delete(Link id);
}
