package edu.hm.ba.kongo.shop.warehouse.client.rest;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

import edu.hm.ba.kongo.shop.warehouse.client.domain.Product_DTO;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.Resource;
import org.springframework.hateoas.Resources;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpMethod;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Product_Resource extends Resource<Product_DTO> {
	/**
     * This is a simple way to get the Resources "class" for the {@link org.springframework.web.client.RestTemplate#exchange(String, HttpMethod, HttpEntity, ParameterizedTypeReference, Object...)}.
     */
    public static final ParameterizedTypeReference<Resources<Product_Resource>> LIST = new ParameterizedTypeReference<Resources<Product_Resource>>() {
    };

    /**
     * Create a new Resource with a blank Product_DTO.
     */
    public Product_Resource() {
        super(new Product_DTO());
    }

    /**
     * Create a new Resource from  a Product_DTO and multiple Resources.
     * @param content The Product_DTO
     * @param links The links to add to the resource
     */
    public Product_Resource(Product_DTO content, Link... links) {
        super(content, links);
    }

    /**
     * Create a new Resource from  a Product_DTO and multiple Resources.
     * @param content The Product_DTO
     * @param links The links to add to the resource
     */
    public Product_Resource(Product_DTO content, Iterable<Link> links) {
        super(content, links);
    }
}
