package edu.hm.ba.kongo.shop.warehouse.client.domain;

import de.muenchen.vaadin.demo.apilib.domain.BaseEntity;
import java.math.BigDecimal;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Product_DTO extends BaseEntity {
	
	private String name;
	
	private String description;
	
	private BigDecimal price;
	
	private long quantity;
	
	// Getters and Setters
	public String getName(){
		return name;
	}
	public void setName(String name){
		this.name = name;
	}
	
	public String getDescription(){
		return description;
	}
	public void setDescription(String description){
		this.description = description;
	}
	
	public BigDecimal getPrice(){
		return price;
	}
	public void setPrice(BigDecimal price){
		this.price = price;
	}
	
	public long getQuantity(){
		return quantity;
	}
	public void setQuantity(long quantity){
		this.quantity = quantity;
	}
	
	@Override
	public String toString() {
	   	return String.format("%s = {\"name\": \"%s\", \"description\": \"%s\", \"price\": \"%s\", \"quantity\": \"%s\"}", getClass(),
	   		this.name,
	   		this.description,
	   		this.price,
	   		this.quantity);
	}
}
