package edu.hm.ba.kongo.shop.shoppingcart.service.services.event;

import org.springframework.stereotype.Service;

import edu.hm.ba.kongo.shop.shoppingcart.service.gen.domain.Cart_;
import edu.hm.ba.kongo.shop.shoppingcart.service.gen.services.event.Cart_EventService;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by Cart_EventListener.
 */
@Service
public class Cart_EventServiceImpl implements Cart_EventService{
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(Cart_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(Cart_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(Cart_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(Cart_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(Cart_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(Cart_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(Cart_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(Cart_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(Cart_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(Cart_ parent, Object linked) {
		// Add your logic here.
	}
}
