package edu.hm.ba.kongo.shop.shoppingcart.service.services.businessactions;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import java.util.Arrays;
import java.util.UUID;
import java.math.BigDecimal;
import java.text.ParseException;
import edu.hm.ba.kongo.shop.shoppingcart.service.gen.services.businessactions.TestDatenBusinessActionService;
import edu.hm.ba.kongo.shop.shoppingcart.service.gen.domain.Cart_;
import edu.hm.ba.kongo.shop.shoppingcart.service.rest.Cart_Repository;
import edu.hm.ba.kongo.shop.shoppingcart.service.gen.domain.CartItem_;

import de.muenchen.service.security.UserInfo;

/**
 * Provides a service to execute business-actions.
 * If used as generated by GAIA this service will be autowired and called by BusinessActionController.
 */
@Service
public class TestDatenBusinessActionServiceImpl implements TestDatenBusinessActionService {
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	@Autowired
	Cart_Repository cartRepo;

	public void testdatenErzeugen(){
		
		//insert example data for Cart_
		Cart_ cart = new Cart_();
		cart.setUserID("123");
		cart.setTotalPrice(new BigDecimal("15.5"));
		cart.setOid(UUID.randomUUID());
		
		//insert example data for CartItem_
		CartItem_ cartItem = new CartItem_();
		cartItem.setProduct("123");
		cartItem.setQuantity(1L);
		
		// Set relations
		
		//Save all example Entities in an order that won't cause errors
		cartRepo.save(cart);
		}

}
