package edu.hm.ba.kongo.shop.shoppingcart.client.hateoas;

import edu.hm.ba.kongo.shop.shoppingcart.client.domain.Cart_DTO;
import edu.hm.ba.kongo.shop.shoppingcart.client.local.Cart_;
import edu.hm.ba.kongo.shop.shoppingcart.client.rest.Cart_Resource;
import org.springframework.hateoas.Resource;
import java.util.stream.Collectors;
import java.util.UUID;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Cart_Assembler {


	/**
	 * Transform the Resource (from the REST Server) to the local object representation.
	 *
	 * @param resource the REST DTO Resource
	 * @return the local Object Representation
	 */
	public Cart_ toBean(Resource<Cart_DTO> resource) {
		Cart_DTO cartDTO = resource.getContent();
		Cart_ bean = new Cart_();		
		bean.setUserID(cartDTO.getUserID());
		bean.setTotalPrice(cartDTO.getTotalPrice());
		CartItem_Assembler itemsAssembler = new CartItem_Assembler();
		bean.setItems(cartDTO.getItems().stream().map(itemsAssembler::toBean).collect(Collectors.toSet()));
				
		bean.add(resource.getLinks());
		
		return bean;
	}
	
	/**
	 * Transform the local object representation to the DTO resource.
	 *
	 * @param bean the local object representation
	 * @return the REST DTO Resource
	 */
	public Cart_Resource toResource(Cart_ bean) {
		return new Cart_Resource(toDTO(bean), bean.getLinks());
	}
	
	/**
	 * Transform the local object representation to the DTO.
	 *
	 * @param bean the local object representation
	 * @return the REST DTO
	 */
	public Cart_DTO toDTO(Cart_ bean) {
		Cart_DTO cartDTO = new Cart_DTO();
		
		try{
			String[] id = bean.getId().getHref().split("/");
			cartDTO.setOid(UUID.fromString(id[id.length-1]));
		} catch(Exception e) {/* No Link found */}
		
		cartDTO.setUserID(bean.getUserID());
		cartDTO.setTotalPrice(bean.getTotalPrice());
		
		CartItem_Assembler itemsAssembler = new CartItem_Assembler();
		cartDTO.setItems(bean.getItems().stream().map(itemsAssembler::toDTO).collect(Collectors.toSet()));
				
		return cartDTO;
	}
}
