package edu.hm.ba.kongo.shop.shoppingcart.client.hateoas;


import edu.hm.ba.kongo.shop.shoppingcart.client.domain.CartItem_DTO;
import edu.hm.ba.kongo.shop.shoppingcart.client.local.CartItem_;
import edu.hm.ba.kongo.shop.shoppingcart.client.domain.CartItem_DTO;
import edu.hm.ba.kongo.shop.shoppingcart.client.local.CartItem_;
import java.util.stream.Collectors;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class CartItem_Assembler {

	/**
	 * Transform the Resource (from the REST Server) to the local object representation.
	 *
	 * @param cartItemDTO the REST DTO Resource
	 * @return the local Object Representation
	 */
	public CartItem_ toBean(CartItem_DTO cartItemDTO) {
		CartItem_ bean = new CartItem_();		bean.setProduct(cartItemDTO.getProduct());
		bean.setQuantity(cartItemDTO.getQuantity());
		return bean;
	}
	
	private CartItem_ toCartItemBean(CartItem_DTO cartItemDTO) {
		CartItem_ cartItem = new CartItem_();
		cartItem.setProduct(cartItemDTO.getProduct());
		cartItem.setQuantity(cartItemDTO.getQuantity());
		return cartItem;
	}
	
	/**
	 * Transform the local object representation to the DTO resource.
	 *
	 * @param bean the local object representation
	 * @return the REST DTO Resource
	 */
	public CartItem_DTO toDTO(CartItem_ bean) {
		CartItem_DTO cartItemDTO = new CartItem_DTO();
		cartItemDTO.setProduct(bean.getProduct());
		cartItemDTO.setQuantity(bean.getQuantity());
		return cartItemDTO;
	}
}
