package edu.hm.ba.kongo.shop.ordering.guilib.services;


import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import edu.hm.ba.kongo.shop.ordering.client.local.Order_;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Order_FallbackDataGenerator{
	
	/** Fallback-Daten generierung. Diese Methoden werden durch Barrakuda mit dem gewünschten Verhalten befüllt. */
	
	
	/**
	 * Generiert Fallback-Daten für Methoden, die einen einzelnen Order_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Order_ createOrderFallback(){
		return null;
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die eine Liste von Order_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static List<Order_> createOrdersFallback(){
		return new ArrayList<>();
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die ein Optional von Order_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Optional<Order_> createOptionalOrderFallback(){
		return Optional.empty();
	}
	
}
