package edu.hm.ba.kongo.shop.ordering.guilib.services;


import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import edu.hm.ba.kongo.shop.ordering.client.local.OrderingItem_;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class OrderingItem_FallbackDataGenerator{
	
	/** Fallback-Daten generierung. Diese Methoden werden durch Barrakuda mit dem gewünschten Verhalten befüllt. */
	
	
	/**
	 * Generiert Fallback-Daten für Methoden, die einen einzelnen OrderingItem_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static OrderingItem_ createOrderingItemFallback(){
		return null;
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die eine Liste von OrderingItem_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static List<OrderingItem_> createOrderingItemsFallback(){
		return new ArrayList<>();
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die ein Optional von OrderingItem_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Optional<OrderingItem_> createOptionalOrderingItemFallback(){
		return Optional.empty();
	}
	
}
