package edu.hm.ba.kongo.shop.ordering.service.services.businessactions;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.Map;

import org.springframework.security.access.prepost.PreAuthorize;
import edu.hm.ba.kongo.shop.ordering.service.gen.services.businessactions.OrderCart_BusinessActionService;

/**
 * Provides a service to execute business-actions.
 * If used as generated by GAIA this service will be autowired and called by BusinessActionController.
 */
@Service
@PreAuthorize("hasAuthority('ordering_BUSINESSACTION_OrderCart')")
public class OrderCart_BusinessActionServiceImpl implements OrderCart_BusinessActionService {
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;

	/**
	 * This BusinessAction's purpose is: Receives a shopping cart to create a new order which can then be payed
	 * TODO: Implement
	 */
	@Override
	public void orderCart(Map<String, Object> header, String cartID){
		// Stop if parameters are null
		java.util.List<String> nullParams = new java.util.ArrayList<>();
		if(cartID==null) nullParams.add("cartID");
		if(!nullParams.isEmpty()){
			throw new IllegalArgumentException("Expected values in body: String cartID - Missing "+nullParams);
		}
		
		throw new UnsupportedOperationException("The BusinessAction ordercart is not yet implemented!");
	}
	
}
