package edu.hm.ba.kongo.shop.ordering.service.services.businessactions;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.Map;

import org.springframework.security.access.prepost.PreAuthorize;
import edu.hm.ba.kongo.shop.ordering.service.gen.services.businessactions.SendInvoice_BusinessActionService;

/**
 * Provides a service to execute business-actions.
 * If used as generated by GAIA this service will be autowired and called by BusinessActionController.
 */
@Service
@PreAuthorize("hasAuthority('ordering_BUSINESSACTION_SendInvoice')")
public class SendInvoice_BusinessActionServiceImpl implements SendInvoice_BusinessActionService {
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;

	/**
	 * This BusinessAction's purpose is: Sends the value of the costs of the ordered procuts to an invoicing system
	 * TODO: Implement
	 */
	@Override
	public void sendInvoice(Map<String, Object> header, String orderID){
		// Stop if parameters are null
		java.util.List<String> nullParams = new java.util.ArrayList<>();
		if(orderID==null) nullParams.add("orderID");
		if(!nullParams.isEmpty()){
			throw new IllegalArgumentException("Expected values in body: String orderID - Missing "+nullParams);
		}
		
		throw new UnsupportedOperationException("The BusinessAction sendinvoice is not yet implemented!");
	}
	
}
