package edu.hm.ba.kongo.shop.ordering.service.services.businessactions;

import edu.hm.ba.kongo.shop.ordering.service.gen.domain.OrderingItem_;
import edu.hm.ba.kongo.shop.ordering.service.gen.services.businessactions.TestDatenBusinessActionService;
import edu.hm.ba.kongo.shop.ordering.service.rest.OrderingItem_Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.UUID;

/**
 * Provides a service to execute business-actions.
 * If used as generated by GAIA this service will be autowired and called by BusinessActionController.
 */
@Service
public class TestDatenBusinessActionServiceImpl implements TestDatenBusinessActionService {
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	@Autowired
	OrderingItem_Repository orderRepo;

	public void testdatenErzeugen(){
		
		//insert example data for Order_
		OrderingItem_ order = new OrderingItem_();
		order.setCart("123");
		order.setOrderedOn(java.time.LocalDate.parse("10.10.2010",java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy")));
		order.setOid(UUID.randomUUID());
		
		// Set relations
		
		//Save all example Entities in an order that won't cause errors
		orderRepo.save(order);
		}

}
