package edu.hm.ba.kongo.shop.ordering.service.services.businessactions;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import java.util.Arrays;
import java.util.UUID;
import java.text.ParseException;
import edu.hm.ba.kongo.shop.ordering.service.gen.services.businessactions.TestDatenBusinessActionService;
import edu.hm.ba.kongo.shop.ordering.service.gen.domain.Order_;
import edu.hm.ba.kongo.shop.ordering.service.rest.Order_Repository;

import de.muenchen.service.security.UserInfo;

/**
 * Provides a service to execute business-actions.
 * If used as generated by GAIA this service will be autowired and called by BusinessActionController.
 */
@Service
public class TestDatenBusinessActionServiceImpl implements TestDatenBusinessActionService {
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	@Autowired
	Order_Repository orderRepo;

	public void testdatenErzeugen(){
		
		//insert example data for Order_
		Order_ order = new Order_();
		order.setCart("123");
		order.setOrderedOn(java.time.LocalDate.parse("10.10.2010",java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy")));
		order.setOid(UUID.randomUUID());
		
		// Set relations
		
		//Save all example Entities in an order that won't cause errors
		orderRepo.save(order);
		}

}
