package edu.hm.ba.kongo.shop.warehouse.service.services.event;

import org.springframework.stereotype.Service;

import edu.hm.ba.kongo.shop.warehouse.service.gen.domain.Product_;
import edu.hm.ba.kongo.shop.warehouse.service.gen.services.event.Product_EventService;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by Product_EventListener.
 */
@Service
public class Product_EventServiceImpl implements Product_EventService{
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(Product_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(Product_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(Product_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(Product_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(Product_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(Product_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(Product_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(Product_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(Product_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(Product_ parent, Object linked) {
		// Add your logic here.
	}
}
