package edu.hm.ba.kongo.shop.shoppingcart.client.rest;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

import edu.hm.ba.kongo.shop.shoppingcart.client.domain.Cart_DTO;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.Resource;
import org.springframework.hateoas.Resources;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpMethod;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Cart_Resource extends Resource<Cart_DTO> {
	/**
     * This is a simple way to get the Resources "class" for the {@link org.springframework.web.client.RestTemplate#exchange(String, HttpMethod, HttpEntity, ParameterizedTypeReference, Object...)}.
     */
    public static final ParameterizedTypeReference<Resources<Cart_Resource>> LIST = new ParameterizedTypeReference<Resources<Cart_Resource>>() {
    };

    /**
     * Create a new Resource with a blank Cart_DTO.
     */
    public Cart_Resource() {
        super(new Cart_DTO());
    }

    /**
     * Create a new Resource from  a Cart_DTO and multiple Resources.
     * @param content The Cart_DTO
     * @param links The links to add to the resource
     */
    public Cart_Resource(Cart_DTO content, Link... links) {
        super(content, links);
    }

    /**
     * Create a new Resource from  a Cart_DTO and multiple Resources.
     * @param content The Cart_DTO
     * @param links The links to add to the resource
     */
    public Cart_Resource(Cart_DTO content, Iterable<Link> links) {
        super(content, links);
    }
}
