package edu.hm.ba.kongo.shop.shoppingcart.client.domain;

import de.muenchen.vaadin.demo.apilib.domain.BaseEntity;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class CartItem_DTO {
	
	private String product;
	
	private long quantity;
	
	// Getters and Setters
	public String getProduct(){
		return product;
	}
	public void setProduct(String product){
		this.product = product;
	}
	
	public long getQuantity(){
		return quantity;
	}
	public void setQuantity(long quantity){
		this.quantity = quantity;
	}
	
	@Override
	public String toString() {
	   	return String.format("%s = {\"product\": \"%s\", \"quantity\": \"%s\"}", getClass(),
	   		this.product,
	   		this.quantity);
	}
}
