package edu.hm.ba.kongo.shop.shoppingcart.client.domain;

import de.muenchen.vaadin.demo.apilib.domain.BaseEntity;
import java.math.BigDecimal;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Cart_DTO extends BaseEntity {
	
	private String userID;
	
	private BigDecimal totalPrice;
	
	private java.util.Set<CartItem_DTO> items;
	
	// Getters and Setters
	public String getUserID(){
		return userID;
	}
	public void setUserID(String userID){
		this.userID = userID;
	}
	
	public BigDecimal getTotalPrice(){
		return totalPrice;
	}
	public void setTotalPrice(BigDecimal totalPrice){
		this.totalPrice = totalPrice;
	}
	
	public java.util.Set<CartItem_DTO> getItems(){
		return items;
	}
	public void setItems(java.util.Set<CartItem_DTO> value){
		this.items = value;
	}
	
	@Override
	public String toString() {
	   	return String.format("%s = {\"userID\": \"%s\", \"totalPrice\": \"%s\"}", getClass(),
	   		this.userID,
	   		this.totalPrice);
	}
}
