package edu.hm.ba.kongo.shop.warehouse.service.services.businessactions;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import java.util.Arrays;
import java.util.UUID;
import java.math.BigDecimal;
import java.text.ParseException;
import edu.hm.ba.kongo.shop.warehouse.service.gen.services.businessactions.TestDatenBusinessActionService;
import edu.hm.ba.kongo.shop.warehouse.service.gen.domain.Product_;
import edu.hm.ba.kongo.shop.warehouse.service.rest.Product_Repository;

import de.muenchen.service.security.UserInfo;

/**
 * Provides a service to execute business-actions.
 * If used as generated by GAIA this service will be autowired and called by BusinessActionController.
 */
@Service
public class TestDatenBusinessActionServiceImpl implements TestDatenBusinessActionService {
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	@Autowired
	Product_Repository productRepo;

	public void testdatenErzeugen(){
		
		//insert example data for Product_
		Product_ product = new Product_();
		product.setName("Bottle");
		product.setDescription("Great for storing water");
		product.setPrice(new BigDecimal("10.5"));
		product.setQuantity(5L);
		product.setOid(UUID.randomUUID());
		
		// Set relations
		
		//Save all example Entities in an order that won't cause errors
		productRepo.save(product);
		}

}
