package edu.hm.ba.kongo.shop.ordering.client.domain;

import de.muenchen.vaadin.demo.apilib.domain.BaseEntity;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.deser.LocalDateDeserializer;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateSerializer;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Order_DTO extends BaseEntity {
	
	private String cart;
	
	@JsonDeserialize(using = LocalDateDeserializer.class)
	@JsonSerialize(using = LocalDateSerializer.class)
	private java.time.LocalDate orderedOn;
	
	// Getters and Setters
	public String getCart(){
		return cart;
	}
	public void setCart(String cart){
		this.cart = cart;
	}
	
	public java.time.LocalDate getOrderedOn(){
		return orderedOn;
	}
	public void setOrderedOn(java.time.LocalDate orderedOn){
		this.orderedOn = orderedOn;
	}
	
	@Override
	public String toString() {
	   	return String.format("%s = {\"cart\": \"%s\", \"orderedOn\": \"%s\"}", getClass(),
	   		this.cart,
	   		this.orderedOn);
	}
}
