package edu.hm.ba.kongo.shop.ordering.client.rest;

import edu.hm.ba.kongo.shop.ordering.client.local.Order_;
import org.springframework.hateoas.Link;

import java.util.Collection;
import java.util.List;
import java.util.Optional;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public interface Order_RestClient {

    /**
     * The name of the Base Endpoint
     */
    public static final String ORDERS = "orders";

    /**
     * Get all the Orders (with matching tenancy).
     *
     * @return a List of all Orders.
     */
    List<Order_> findAll();

    /**
     * Get all the Orders (with matching tenancy) on a specific endpoint.
     * <p>
     *     For example: <code>http://localhost:80/entitys/1/attribute</code>
     * </p>
     * @param relation
     * @return
     */
    List<Order_> findAll(Link relation);
    
    /**
     * Get all Order matched with string due to fuzzy search.
     * @param filter the string for the query
     * @return
     */
    List<Order_> findFullTextFuzzy(String filter);

    /**
     * Try to find one Order (with matching tenancy) by its ID / self relation.
     *
     * @param link The ID / self relation of the Order_.
     * @return an optional of the Order_.
     */
    Optional<Order_> findOne(Link link);

    /**
     * Set all the relations, specified by links, on a specific relation endpoint.
     * <p>
     * Example for an Endpoint: <code>http://localhost:80/entitys/1/attribute</code>
     * </p>
     * <p>
     * This method will always (re-) set the associations. The add or delete
     * functionality is not provided at RestClient level.
     * </p>
     *
     * @param endpoint The endpoint of the relation.
     * @param links    The links that are set to be related.
     */
    void setRelations(Link endpoint, Collection<Link> links);
	/**
	 * Set the relation, specified by @relation, on a specific relation endpoint.
	 * <p>
	 * Example for an Endpoint: <code>http://localhost:80/entitys/1/attribute</code>
	 * </p>
	 * <p>
	 * This method will always (re-) set the association. The add or delete
	 * functionality is not provided at RestClient level.
	 * </p>
	 *
	 * @param endpoint The endpoint of the relation.
	 * @param relation    The link that is set to be related.
	 */
	void setRelation(Link endpoint, Link relation);
    /**
     * Create a new Order_, the returned Order_ will have the Links and its ID.
     * @param order The Order_ to create, it must not contain any links.
     * @return the created Order_ (with ID).
     */
    Order_ create(Order_ order);

    /**
     * Update the fields of a Order_ by the {@link Order_#getId()}.
     *
     * @param order The updated Order_ that will be saved.
     * @return the updated version from the REST Server.
     */
    Order_ update(Order_ order);

    /**
     * Try to delete an ID.
     * @param id The link to the id.
     */
    void delete(Link id);
}
