package edu.hm.ba.kongo.shop.ordering.client.rest;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

import edu.hm.ba.kongo.shop.ordering.client.domain.OrderingItem_DTO;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.Resource;
import org.springframework.hateoas.Resources;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpMethod;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class OrderingItem_Resource extends Resource<OrderingItem_DTO> {
	/**
     * This is a simple way to get the Resources "class" for the {@link org.springframework.web.client.RestTemplate#exchange(String, HttpMethod, HttpEntity, ParameterizedTypeReference, Object...)}.
     */
    public static final ParameterizedTypeReference<Resources<OrderingItem_Resource>> LIST = new ParameterizedTypeReference<Resources<OrderingItem_Resource>>() {
    };

    /**
     * Create a new Resource with a blank OrderingItem_DTO.
     */
    public OrderingItem_Resource() {
        super(new OrderingItem_DTO());
    }

    /**
     * Create a new Resource from  a OrderingItem_DTO and multiple Resources.
     * @param content The OrderingItem_DTO
     * @param links The links to add to the resource
     */
    public OrderingItem_Resource(OrderingItem_DTO content, Link... links) {
        super(content, links);
    }

    /**
     * Create a new Resource from  a OrderingItem_DTO and multiple Resources.
     * @param content The OrderingItem_DTO
     * @param links The links to add to the resource
     */
    public OrderingItem_Resource(OrderingItem_DTO content, Iterable<Link> links) {
        super(content, links);
    }
}
